server:
  port: 6001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.94.226:8848     #配置注册中心地址
    gateway:
      discovery:
        locator:
          enabled: false                #根据服务id自动路由
          lowerCaseServiceId: true
      routes:
      - id: role-client                 #我们自定义的路由ID,没有规定规则但要求唯一,建议配合服务名
        uri: lb://role-client           #lb://是指当前注册中心下  后面的是微服务的名字
        predicates:
          - Path=/role-api/**
        filters:
          - StripPrefix=1
      - id: user-client
        uri: lb://user-client
        predicates:
          - Path=/user-api/**
        filters:
          - StripPrefix=1
      - id: security-client
        uri: lb://security-client
        predicates:
          - Path=/security-api/**
        filters:
          - StripPrefix=1