server:
  port: 6001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false      #根据服务id自动路由
          lowerCaseServiceId: true
      routes:
      - id: role-client
        uri: lb://role-client
        predicates:
          - Path=/role/**
        filters:
          - StripPrefix=1
      - id: user-client
        uri: lb://user-client
        predicates:
          - Path=/user/**
        filters:
          - StripPrefix=1