server:
  port: 4001
spring:
  application:
    name: role-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    #配置文件:dev(开发环境)
    url: jdbc:mysql://120.79.94.226:3306/springcloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
feign:
  hystrix:
    enabled: true     #开启Feign的熔断功能（Feign集成Hystrix默认是不开启熔断功能的，需要手动开启）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
