server:
  port: 5001
spring:
  application:
    name: security-client
  redis:
    database: 0
    host: 120.79.94.226
    port: 6379
    timeout: 10000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    #配置文件:dev(开发环境)
    url: jdbc:mysql://120.79.94.226:3306/springcloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
jedis:
  host: 120.79.94.226
  password:
  port: 6379
  timeout: 2000
  maxTotal: 15 # 最大连接数
  maxIdle: 10 # 最大空闲连接
  minIdle: 5 # 最小空闲连接
  maxWaitMillis: 10000 # 获取连接最大等待时间
  testOnBorrow: true # 获取连接时检测是否可用
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng

